BEGIN;

CREATE USER sptt WITH PASSWORD 'pwd666123';

GRANT CONNECT ON DATABASE steamtrack TO sptt;
GRANT USAGE, CREATE ON SCHEMA public TO sptt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sptt;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sptt;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sptt;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO sptt;

COMMIT;